export interface CatalogProduct {
  id: string;
  name: string;
  name_hi: string;
  brand: string;
  category: string;
  price_inr: number;
  url: string;
  description: string;
  styles: string[]; // which design styles this fits
}

// Curated catalog of real Indian home decor products
// Sources: IKEA India (ikea.com/in/en), Amazon India, Pepperfry
export const PRODUCT_CATALOG: CatalogProduct[] = [
  // ── FURNITURE: BEDS ────────────────────────────────────────────────
  {
    id: "FU001",
    name: "HEMNES Bed Frame (White Stain)",
    name_hi: "हेमनेस बेड फ्रेम (सफेद)",
    brand: "IKEA",
    category: "Bed",
    price_inr: 34990,
    url: "https://www.ikea.com/in/en/search/?q=HEMNES+bed+frame",
    description: "Solid wood bed in classic white stain; timeless look with hidden storage option",
    styles: ["Modern Indian", "Minimalist"],
  },
  {
    id: "FU002",
    name: "MALM Bed Frame (Black-Brown)",
    name_hi: "माल्म बेड फ्रेम (काला-भूरा)",
    brand: "IKEA",
    category: "Bed",
    price_inr: 24990,
    url: "https://www.ikea.com/in/en/search/?q=MALM+bed+frame",
    description: "Clean-lined bed with veneer surface; sleek modern aesthetic",
    styles: ["Minimalist"],
  },
  {
    id: "FU003",
    name: "BRIMNES Bed Frame with Storage",
    name_hi: "ब्रिमनेस बेड फ्रेम (स्टोरेज)",
    brand: "IKEA",
    category: "Bed",
    price_inr: 19990,
    url: "https://www.ikea.com/in/en/search/?q=BRIMNES+bed+frame+storage",
    description: "Headboard with shelves and under-bed drawers; practical for smaller rooms",
    styles: ["Minimalist", "Vastu-Optimized"],
  },
  {
    id: "FU004",
    name: "NORDLI Bed with Storage (White)",
    name_hi: "नॉर्डली बेड (सफेद, स्टोरेज)",
    brand: "IKEA",
    category: "Bed",
    price_inr: 29990,
    url: "https://www.ikea.com/in/en/search/?q=NORDLI+bed+storage",
    description: "Modular storage bed in white; reduces floor clutter aligning with Vastu",
    styles: ["Minimalist", "Vastu-Optimized"],
  },

  // ── FURNITURE: SOFAS ───────────────────────────────────────────────
  {
    id: "FU005",
    name: "KIVIK 3-Seat Sofa (Tibbleby Beige)",
    name_hi: "किविक 3-सीट सोफा (बेज)",
    brand: "IKEA",
    category: "Sofa",
    price_inr: 44990,
    url: "https://www.ikea.com/in/en/search/?q=KIVIK+3+seat+sofa",
    description: "Deep-seated comfortable sofa with cushioned back; neutral beige",
    styles: ["Minimalist", "Vastu-Optimized"],
  },
  {
    id: "FU006",
    name: "SÖDERHAMN 3-Seat Sofa (Finnsta Turquoise)",
    name_hi: "सोडरहामन सोफा (टर्कोइज़)",
    brand: "IKEA",
    category: "Sofa",
    price_inr: 74990,
    url: "https://www.ikea.com/in/en/search/?q=SÖDERHAMN+sofa",
    description: "Low-profile modular sofa in teal-turquoise; vibrant modern statement",
    styles: ["Modern Indian"],
  },
  {
    id: "FU007",
    name: "EKTORP 2-Seat Sofa (Vittaryd White)",
    name_hi: "एक्टॉर्प 2-सीट सोफा (सफेद)",
    brand: "IKEA",
    category: "Sofa",
    price_inr: 39990,
    url: "https://www.ikea.com/in/en/search/?q=EKTORP+sofa",
    description: "Classic Scandinavian sofa with washable covers in crisp white",
    styles: ["Minimalist"],
  },
  {
    id: "FU008",
    name: "POÄNG Armchair (Knisa Beige)",
    name_hi: "पोएंग आर्मचेयर (बेज)",
    brand: "IKEA",
    category: "Chair",
    price_inr: 8990,
    url: "https://www.ikea.com/in/en/search/?q=POANG+armchair",
    description: "Bent birch frame armchair; ergonomic and lightweight",
    styles: ["Minimalist", "Vastu-Optimized"],
  },
  {
    id: "FU009",
    name: "STEFAN Chair (Set of 2, Brown-Black)",
    name_hi: "स्टेफन चेयर (2 का सेट)",
    brand: "IKEA",
    category: "Chair",
    price_inr: 3990,
    url: "https://www.ikea.com/in/en/search/?q=STEFAN+chair",
    description: "Solid beech wood chair in brown-black stain; clean traditional form",
    styles: ["Modern Indian", "Minimalist"],
  },

  // ── FURNITURE: TABLES ──────────────────────────────────────────────
  {
    id: "FU010",
    name: "LISABO Dining Table (Ash Veneer, 140x78 cm)",
    name_hi: "लिसाबो डाइनिंग टेबल",
    brand: "IKEA",
    category: "Dining Table",
    price_inr: 15990,
    url: "https://www.ikea.com/in/en/search/?q=LISABO+dining+table",
    description: "Solid ash veneer legs with distinct natural grain; Japanese-influenced",
    styles: ["Minimalist", "Modern Indian"],
  },
  {
    id: "FU011",
    name: "EKEDALEN Extendable Dining Table",
    name_hi: "एकेडालेन एक्सटेंडेबल डाइनिंग टेबल",
    brand: "IKEA",
    category: "Dining Table",
    price_inr: 19990,
    url: "https://www.ikea.com/in/en/search/?q=EKEDALEN+table",
    description: "Extends to seat up to 8 people; practical for Indian joint families",
    styles: ["Modern Indian", "Vastu-Optimized"],
  },
  {
    id: "FU012",
    name: "LACK Coffee Table (White)",
    name_hi: "लैक कॉफी टेबल (सफेद)",
    brand: "IKEA",
    category: "Coffee Table",
    price_inr: 1990,
    url: "https://www.ikea.com/in/en/search/?q=LACK+coffee+table+white",
    description: "Minimalist low table with shelf underneath; keeps living room clear",
    styles: ["Minimalist", "Vastu-Optimized"],
  },
  {
    id: "FU013",
    name: "LACK Side Table (Black-Brown)",
    name_hi: "लैक साइड टेबल",
    brand: "IKEA",
    category: "Side Table",
    price_inr: 1299,
    url: "https://www.ikea.com/in/en/search/?q=LACK+side+table",
    description: "Compact side table that fits next to sofa or bed",
    styles: ["Minimalist"],
  },
  {
    id: "FU014",
    name: "HEMNES TV Storage Combination (White)",
    name_hi: "हेमनेस टीवी यूनिट (सफेद)",
    brand: "IKEA",
    category: "TV Unit",
    price_inr: 19990,
    url: "https://www.ikea.com/in/en/search/?q=HEMNES+TV+storage",
    description: "Classic TV cabinet with drawers in solid white-stained pine",
    styles: ["Modern Indian", "Minimalist"],
  },

  // ── STORAGE ────────────────────────────────────────────────────────
  {
    id: "ST001",
    name: "BILLY Bookcase (White, 80x28x202 cm)",
    name_hi: "बिली बुककेस (सफेद)",
    brand: "IKEA",
    category: "Shelving",
    price_inr: 5990,
    url: "https://www.ikea.com/in/en/search/?q=BILLY+bookcase",
    description: "Iconic adjustable bookcase in white; fits any wall seamlessly",
    styles: ["Minimalist", "Vastu-Optimized"],
  },
  {
    id: "ST002",
    name: "KALLAX Shelf Unit (2×2, White)",
    name_hi: "कैलेक्स शेल्फ यूनिट (2×2, सफेद)",
    brand: "IKEA",
    category: "Shelving",
    price_inr: 7990,
    url: "https://www.ikea.com/in/en/search/?q=KALLAX+shelf+unit+2x2",
    description: "Cube shelf doubles as room divider or TV stand; great for display",
    styles: ["Modern Indian", "Minimalist"],
  },
  {
    id: "ST003",
    name: "KALLAX Shelf Unit (4×4, White)",
    name_hi: "कैलेक्स शेल्फ यूनिट (4×4, सफेद)",
    brand: "IKEA",
    category: "Shelving",
    price_inr: 14990,
    url: "https://www.ikea.com/in/en/search/?q=KALLAX+shelf+unit+4x4",
    description: "Large cube storage unit; can hold baskets, boxes, or display items",
    styles: ["Minimalist", "Vastu-Optimized"],
  },
  {
    id: "ST004",
    name: "HEMNES 6-Drawer Chest (White)",
    name_hi: "हेमनेस 6-ड्रॉअर चेस्ट (सफेद)",
    brand: "IKEA",
    category: "Dresser",
    price_inr: 24990,
    url: "https://www.ikea.com/in/en/search/?q=HEMNES+6+drawer+chest",
    description: "Solid pine wood chest of drawers in classic white stain",
    styles: ["Modern Indian", "Minimalist"],
  },
  {
    id: "ST005",
    name: "MALM 6-Drawer Chest (White)",
    name_hi: "माल्म 6-ड्रॉअर चेस्ट",
    brand: "IKEA",
    category: "Dresser",
    price_inr: 19990,
    url: "https://www.ikea.com/in/en/search/?q=MALM+6+drawer+chest",
    description: "Smooth veneer surface dresser with push-to-open drawers",
    styles: ["Minimalist"],
  },

  // ── LIGHTING ───────────────────────────────────────────────────────
  {
    id: "LI001",
    name: "RANARP Floor Lamp (Off-White)",
    name_hi: "रानार्प फ्लोर लैंप (ऑफ-व्हाइट)",
    brand: "IKEA",
    category: "Lighting",
    price_inr: 4490,
    url: "https://www.ikea.com/in/en/search/?q=RANARP+floor+lamp",
    description: "Industrial-style adjustable floor lamp in off-white; warm ambient light",
    styles: ["Modern Indian", "Minimalist"],
  },
  {
    id: "LI002",
    name: "HEKTAR Pendant Lamp (Dark Gray)",
    name_hi: "हेक्टर पेंडेंट लैंप (डार्क ग्रे)",
    brand: "IKEA",
    category: "Lighting",
    price_inr: 4990,
    url: "https://www.ikea.com/in/en/search/?q=HEKTAR+pendant+lamp",
    description: "Classic industrial pendant in dark metal; focuses light downward",
    styles: ["Modern Indian", "Minimalist"],
  },
  {
    id: "LI003",
    name: "TÄRNABY Table Lamp (Orange)",
    name_hi: "टार्नाबी टेबल लैंप (नारंगी)",
    brand: "IKEA",
    category: "Lighting",
    price_inr: 1490,
    url: "https://www.ikea.com/in/en/search/?q=TÄRNABY+table+lamp",
    description: "Saffron-orange fabric shade table lamp; pops of color for Indian style",
    styles: ["Modern Indian"],
  },
  {
    id: "LI004",
    name: "SINNERLIG Pendant Lamp (Bamboo)",
    name_hi: "सिनरलिग पेंडेंट लैंप (बांस)",
    brand: "IKEA",
    category: "Lighting",
    price_inr: 3490,
    url: "https://www.ikea.com/in/en/search/?q=SINNERLIG+pendant+lamp",
    description: "Hand-crafted bamboo pendant shade; natural material for positive energy",
    styles: ["Vastu-Optimized", "Modern Indian"],
  },
  {
    id: "LI005",
    name: "Handcrafted Brass Diya Stand (Set of 3)",
    name_hi: "पीतल की दीया स्टैंड (3 का सेट)",
    brand: "Amazon",
    category: "Lighting",
    price_inr: 1299,
    url: "https://www.amazon.in/s?k=brass+diya+stand+set+home+decor",
    description: "Traditional brass oil lamp holders; enhances Vastu-positive energy",
    styles: ["Modern Indian", "Vastu-Optimized"],
  },
  {
    id: "LI006",
    name: "SOLVINDEN LED String Lights (Outdoor/Indoor)",
    name_hi: "सॉल्विंडेन LED स्ट्रिंग लाइट्स",
    brand: "IKEA",
    category: "Lighting",
    price_inr: 1990,
    url: "https://www.ikea.com/in/en/search/?q=SOLVINDEN+LED+string+lights",
    description: "Solar/battery powered warm-white fairy lights for festive atmosphere",
    styles: ["Modern Indian"],
  },

  // ── TEXTILES & RUGS ────────────────────────────────────────────────
  {
    id: "TX001",
    name: "GURLI Cushion Cover Set (50×50 cm, Curry)",
    name_hi: "गुरली कुशन कवर (करी येलो)",
    brand: "IKEA",
    category: "Cushion",
    price_inr: 699,
    url: "https://www.ikea.com/in/en/search/?q=GURLI+cushion+cover+curry",
    description: "Cotton cushion covers in warm curry yellow; saffron accent",
    styles: ["Modern Indian", "Vastu-Optimized"],
  },
  {
    id: "TX002",
    name: "SANELA Curtains (1 pair, Red-Brown, 140×250 cm)",
    name_hi: "सनेला पर्दे (लाल-भूरा)",
    brand: "IKEA",
    category: "Curtains",
    price_inr: 2999,
    url: "https://www.ikea.com/in/en/search/?q=SANELA+curtains",
    description: "Velvet curtains in deep red-brown; blocks light, adds richness",
    styles: ["Modern Indian"],
  },
  {
    id: "TX003",
    name: "HANNALILL Curtains (1 pair, White, 140×250 cm)",
    name_hi: "हन्नालिल पर्दे (सफेद)",
    brand: "IKEA",
    category: "Curtains",
    price_inr: 1499,
    url: "https://www.ikea.com/in/en/search/?q=HANNALILL+curtains",
    description: "Sheer lightweight curtains in white; lets in natural light",
    styles: ["Minimalist", "Vastu-Optimized"],
  },
  {
    id: "TX004",
    name: "STOENSE Rug (Off-White, 160×230 cm)",
    name_hi: "स्टोएन्से रग (ऑफ-व्हाइट)",
    brand: "IKEA",
    category: "Rug",
    price_inr: 4490,
    url: "https://www.ikea.com/in/en/search/?q=STOENSE+rug",
    description: "Low-pile easy-clean rug in off-white; grounding minimalist base",
    styles: ["Minimalist", "Vastu-Optimized"],
  },
  {
    id: "TX005",
    name: "ALPDRABA Rug (Blue/White, 160×230 cm)",
    name_hi: "अल्पड्राबा रग (नीला/सफेद)",
    brand: "IKEA",
    category: "Rug",
    price_inr: 5990,
    url: "https://www.ikea.com/in/en/search/?q=ALPDRABA+rug",
    description: "Hand-woven flatwoven rug with geometric pattern in blue and white",
    styles: ["Modern Indian", "Vastu-Optimized"],
  },
  {
    id: "TX006",
    name: "Rajasthani Block Print Bedspread (Queen)",
    name_hi: "राजस्थानी ब्लॉक प्रिंट बेडस्प्रेड",
    brand: "Amazon",
    category: "Bedding",
    price_inr: 2499,
    url: "https://www.amazon.in/s?k=rajasthani+block+print+bedspread+queen",
    description: "Hand block-printed cotton bedspread in traditional Indian motifs",
    styles: ["Modern Indian"],
  },
  {
    id: "TX007",
    name: "Jute Braided Area Rug (5×7 ft, Natural)",
    name_hi: "जूट ब्रेडेड एरिया रग (नेचुरल)",
    brand: "Amazon",
    category: "Rug",
    price_inr: 3499,
    url: "https://www.amazon.in/s?k=jute+braided+area+rug+5x7+natural",
    description: "Natural fiber rug; grounding earth element per Vastu Shastra",
    styles: ["Vastu-Optimized", "Modern Indian"],
  },
  {
    id: "TX008",
    name: "DVALA Duvet Cover Set (White, 200×200 cm)",
    name_hi: "डवाला डुवेट कवर सेट (सफेद)",
    brand: "IKEA",
    category: "Bedding",
    price_inr: 2490,
    url: "https://www.ikea.com/in/en/search/?q=DVALA+duvet+cover",
    description: "100% cotton duvet cover with pillowcases in pure white",
    styles: ["Minimalist"],
  },

  // ── DECOR & ACCESSORIES ────────────────────────────────────────────
  {
    id: "DC001",
    name: "FEJKA Artificial Bamboo Plant (Indoor)",
    name_hi: "फेजका आर्टिफिशियल बांस का पौधा",
    brand: "IKEA",
    category: "Plants",
    price_inr: 1990,
    url: "https://www.ikea.com/in/en/search/?q=FEJKA+artificial+bamboo",
    description: "Lifelike bamboo in a pot; brings nature indoors without maintenance",
    styles: ["Vastu-Optimized", "Minimalist"],
  },
  {
    id: "DC002",
    name: "SATSUMAS Plant Pot with Saucer (Set of 3)",
    name_hi: "सेट्समास प्लांट पॉट (3 का सेट)",
    brand: "IKEA",
    category: "Plants",
    price_inr: 599,
    url: "https://www.ikea.com/in/en/search/?q=SATSUMAS+plant+pot",
    description: "Terracotta-style pots in three sizes; natural earth element",
    styles: ["Modern Indian", "Vastu-Optimized"],
  },
  {
    id: "DC003",
    name: "Brass Ganesha Figurine (Antique Finish, 6 inch)",
    name_hi: "पीतल गणेश मूर्ति (6 इंच)",
    brand: "Amazon",
    category: "Spiritual Decor",
    price_inr: 1199,
    url: "https://www.amazon.in/s?k=brass+ganesha+figurine+antique+home+decor",
    description: "Handcrafted brass Ganesha; auspicious Vastu placement at entrance",
    styles: ["Modern Indian", "Vastu-Optimized"],
  },
  {
    id: "DC004",
    name: "Madhubani Art Print (Framed, 12×16 inch)",
    name_hi: "मधुबनी आर्ट प्रिंट (फ्रेम सहित)",
    brand: "Amazon",
    category: "Wall Art",
    price_inr: 1499,
    url: "https://www.amazon.in/s?k=madhubani+art+print+framed+wall+decor",
    description: "Traditional Bihar folk art print with vibrant colors and motifs",
    styles: ["Modern Indian"],
  },
  {
    id: "DC005",
    name: "RIBBA Picture Frame (White, 50×70 cm)",
    name_hi: "रिब्बा पिक्चर फ्रेम (सफेद)",
    brand: "IKEA",
    category: "Wall Art",
    price_inr: 799,
    url: "https://www.ikea.com/in/en/search/?q=RIBBA+picture+frame+50x70",
    description: "Gallery-quality frame with mat in pure white; suits any poster",
    styles: ["Minimalist"],
  },
  {
    id: "DC006",
    name: "Set of 3 Handpainted Terracotta Pots",
    name_hi: "3 हस्तनिर्मित टेराकोटा मिट्टी के बर्तन",
    brand: "Amazon",
    category: "Plants",
    price_inr: 899,
    url: "https://www.amazon.in/s?k=handpainted+terracotta+plant+pots+set",
    description: "Hand-painted terracotta pots with Indian folk motifs; earthy character",
    styles: ["Modern Indian", "Vastu-Optimized"],
  },
  {
    id: "DC007",
    name: "STOCKHOLM Vase (Patterned, 24 cm)",
    name_hi: "स्टॉकहोम फूलदान (24 सेमी)",
    brand: "IKEA",
    category: "Decor",
    price_inr: 1490,
    url: "https://www.ikea.com/in/en/search/?q=STOCKHOLM+vase",
    description: "Handmade glass vase with intricate patterned surface; artisan finish",
    styles: ["Modern Indian", "Minimalist"],
  },
  {
    id: "DC008",
    name: "Warli Tribal Art Canvas Print (Set of 2)",
    name_hi: "वारली आदिवासी कला कैनवास (2 का सेट)",
    brand: "Amazon",
    category: "Wall Art",
    price_inr: 1999,
    url: "https://www.amazon.in/s?k=warli+art+canvas+print+set+wall+decor",
    description: "Black-and-white tribal Warli paintings on canvas; cultural heritage wall decor",
    styles: ["Modern Indian", "Minimalist"],
  },
  {
    id: "DC009",
    name: "SATSUMAS Plant Pot (Large, Dark Green)",
    name_hi: "सेट्समास बड़ा प्लांट पॉट (गहरा हरा)",
    brand: "IKEA",
    category: "Plants",
    price_inr: 799,
    url: "https://www.ikea.com/in/en/search/?q=SATSUMAS+plant+pot+large",
    description: "Large indoor plant pot in deep green; brings life energy per Vastu",
    styles: ["Vastu-Optimized"],
  },

  // ── MATTRESS & BEDDING ─────────────────────────────────────────────
  {
    id: "BD001",
    name: "MORGEDAL Foam Mattress (Queen, Firm)",
    name_hi: "मॉर्गेडल फोम मैट्रेस (क्वीन)",
    brand: "IKEA",
    category: "Mattress",
    price_inr: 11990,
    url: "https://www.ikea.com/in/en/search/?q=MORGEDAL+foam+mattress",
    description: "Foam mattress with firm support; ergonomic spine alignment",
    styles: ["Minimalist", "Vastu-Optimized"],
  },
  {
    id: "BD002",
    name: "ÅFJÄLL Pillow (Pair, Soft)",
    name_hi: "ओफजॉल तकिया (जोड़ा, सॉफ्ट)",
    brand: "IKEA",
    category: "Bedding",
    price_inr: 1299,
    url: "https://www.ikea.com/in/en/search/?q=ÅFJÄLL+pillow",
    description: "Soft down-alternative pillows; neck-supporting ergonomic shape",
    styles: ["Minimalist", "Modern Indian"],
  },

  // ── PEPPERFRY ──────────────────────────────────────────────────────
  {
    id: "PF001",
    name: "Nilambari 3-Seater Fabric Sofa (Teal)",
    name_hi: "निलांबरी 3-सीटर फैब्रिक सोफा (टील)",
    brand: "Pepperfry",
    category: "Sofa",
    price_inr: 32990,
    url: "https://www.pepperfry.com/search?q=3+seater+fabric+sofa+teal",
    description: "Cushioned back 3-seater in teal fabric; vibrant and spacious for Indian living rooms",
    styles: ["Modern Indian", "Vastu-Optimized"],
  },
  {
    id: "PF002",
    name: "Sheesham Wood Queen Bed with Storage",
    name_hi: "शीशम लकड़ी क्वीन बेड (स्टोरेज सहित)",
    brand: "Pepperfry",
    category: "Bed",
    price_inr: 28990,
    url: "https://www.pepperfry.com/search?q=sheesham+wood+queen+bed+storage",
    description: "Solid sheesham wood bed with hydraulic storage; natural grain, built to last",
    styles: ["Modern Indian", "Vastu-Optimized"],
  },
  {
    id: "PF003",
    name: "Mango Wood 4-Seater Dining Set",
    name_hi: "मैंगो वुड 4-सीटर डाइनिंग सेट",
    brand: "Pepperfry",
    category: "Dining Table",
    price_inr: 18990,
    url: "https://www.pepperfry.com/search?q=mango+wood+4+seater+dining+set",
    description: "Solid mango wood table with 4 chairs; warm honey finish ideal for Indian homes",
    styles: ["Modern Indian", "Vastu-Optimized"],
  },
  {
    id: "PF004",
    name: "Engineered Wood TV Unit with LED (180 cm)",
    name_hi: "इंजीनियर्ड वुड TV यूनिट LED सहित",
    brand: "Pepperfry",
    category: "TV Unit",
    price_inr: 12990,
    url: "https://www.pepperfry.com/search?q=tv+unit+led+180cm+engineered+wood",
    description: "Floating TV unit with ambient LED strip; walnut finish with open shelves",
    styles: ["Modern Indian", "Minimalist"],
  },
  {
    id: "PF005",
    name: "Sheesham Wood Bookshelf (5-Tier)",
    name_hi: "शीशम वुड बुकशेल्फ (5-टियर)",
    brand: "Pepperfry",
    category: "Shelving",
    price_inr: 8990,
    url: "https://www.pepperfry.com/search?q=sheesham+wood+bookshelf+5+tier",
    description: "Solid sheesham wood 5-shelf unit with rustic natural finish",
    styles: ["Modern Indian", "Vastu-Optimized"],
  },
  {
    id: "PF006",
    name: "Wooden Coffee Table (Nested, Set of 2)",
    name_hi: "नेस्टेड कॉफी टेबल (2 का सेट)",
    brand: "Pepperfry",
    category: "Coffee Table",
    price_inr: 6990,
    url: "https://www.pepperfry.com/search?q=nested+coffee+table+wooden+set",
    description: "Two nesting tables in warm walnut finish; space-saving design",
    styles: ["Modern Indian", "Minimalist"],
  },

  // ── URBAN LADDER ───────────────────────────────────────────────────
  {
    id: "UL001",
    name: "Hamden 3-Seater Sofa (Dark Walnut)",
    name_hi: "हैम्डेन 3-सीटर सोफा (डार्क वॉलनट)",
    brand: "Urban Ladder",
    category: "Sofa",
    price_inr: 44999,
    url: "https://www.urbanladder.com/search?q=hamden+3+seater+sofa",
    description: "Premium solid walnut frame with high-density foam; deep-seated contemporary sofa",
    styles: ["Minimalist", "Modern Indian"],
  },
  {
    id: "UL002",
    name: "Edith Queen Bed (Solid Walnut Wood)",
    name_hi: "एडिथ क्वीन बेड (वॉलनट लकड़ी)",
    brand: "Urban Ladder",
    category: "Bed",
    price_inr: 35999,
    url: "https://www.urbanladder.com/search?q=queen+bed+solid+walnut",
    description: "Solid walnut wood queen bed; minimalist profile with clean joinery",
    styles: ["Minimalist"],
  },
  {
    id: "UL003",
    name: "Alto Bookshelf (Ladder Style, Walnut)",
    name_hi: "ऑल्टो लैडर बुकशेल्फ (वॉलनट)",
    brand: "Urban Ladder",
    category: "Shelving",
    price_inr: 10999,
    url: "https://www.urbanladder.com/search?q=alto+ladder+bookshelf+walnut",
    description: "Leaning ladder shelf in solid walnut; open design lets the wall breathe",
    styles: ["Minimalist", "Modern Indian"],
  },
  {
    id: "UL004",
    name: "Fiona Study Table with Drawer (White Oak)",
    name_hi: "फियोना स्टडी टेबल (व्हाइट ओक)",
    brand: "Urban Ladder",
    category: "Dining Table",
    price_inr: 13999,
    url: "https://www.urbanladder.com/search?q=study+table+white+oak+drawer",
    description: "Compact solid wood desk with single drawer; Scandinavian-Indian minimal style",
    styles: ["Minimalist"],
  },
  {
    id: "UL005",
    name: "Renee 2-Door Wardrobe (White)",
    name_hi: "रेनी 2-दरवाजा वॉर्डरोब (सफेद)",
    brand: "Urban Ladder",
    category: "Dresser",
    price_inr: 24999,
    url: "https://www.urbanladder.com/search?q=2+door+wardrobe+white",
    description: "Engineered wood wardrobe in clean white; full-length mirror door option",
    styles: ["Minimalist"],
  },

  // ── FABINDIA ───────────────────────────────────────────────────────
  {
    id: "FI001",
    name: "Hand Block Print Cushion Covers (Set of 5, Indigo)",
    name_hi: "हैंड ब्लॉक प्रिंट कुशन कवर (5 का सेट, इंडिगो)",
    brand: "Fabindia",
    category: "Cushion",
    price_inr: 1495,
    url: "https://www.fabindia.com/home/home-furnishings/cushion-covers",
    description: "Hand block-printed cotton cushion covers in indigo blue with geometric motifs",
    styles: ["Modern Indian", "Vastu-Optimized"],
  },
  {
    id: "FI002",
    name: "Dabu Hand Block Print Curtains (Set of 2, Earthy Red)",
    name_hi: "दाबू हैंड ब्लॉक प्रिंट पर्दे (2 का सेट, लाल)",
    brand: "Fabindia",
    category: "Curtains",
    price_inr: 2990,
    url: "https://www.fabindia.com/home/home-furnishings/curtains-and-blinds",
    description: "Dabu resist-dyed cotton curtains; traditional Rajasthani craft in earthy red",
    styles: ["Modern Indian"],
  },
  {
    id: "FI003",
    name: "Kalamkari Printed Bedsheet Set (King)",
    name_hi: "कलमकारी प्रिंटेड बेडशीट सेट (किंग)",
    brand: "Fabindia",
    category: "Bedding",
    price_inr: 3490,
    url: "https://www.fabindia.com/home/home-furnishings/bed-linen",
    description: "Kalamkari hand-painted cotton bedsheet with 2 pillowcases; Andhra art tradition",
    styles: ["Modern Indian"],
  },
  {
    id: "FI004",
    name: "Cotton Dhurrie Flat Weave Rug (4×6 ft)",
    name_hi: "कॉटन धुर्री रग (4×6 फीट)",
    brand: "Fabindia",
    category: "Rug",
    price_inr: 4290,
    url: "https://www.fabindia.com/home/home-furnishings/rugs-and-durries",
    description: "Handwoven cotton dhurrie in earthy tones; traditional Indian flatweave",
    styles: ["Modern Indian", "Vastu-Optimized"],
  },
  {
    id: "FI005",
    name: "Ajrakh Print Table Runner & Placemats Set",
    name_hi: "अजरख प्रिंट टेबल रनर और प्लेसमैट सेट",
    brand: "Fabindia",
    category: "Decor",
    price_inr: 1195,
    url: "https://www.fabindia.com/home/home-furnishings/table-linen",
    description: "Ajrakh block-printed cotton table runner with 4 placemats; Kutchi craft",
    styles: ["Modern Indian"],
  },
  {
    id: "FI006",
    name: "Handloom Cotton Throw Blanket (Indigo Stripes)",
    name_hi: "हैंडलूम कॉटन थ्रो ब्लैंकेट (इंडिगो स्ट्राइप्स)",
    brand: "Fabindia",
    category: "Bedding",
    price_inr: 1990,
    url: "https://www.fabindia.com/home/home-furnishings/throws-and-blankets",
    description: "Handloom woven cotton throw in classic indigo stripes; drapes beautifully over sofas",
    styles: ["Modern Indian", "Minimalist"],
  },

  // ── WOODENSTREET ───────────────────────────────────────────────────
  {
    id: "WS001",
    name: "Sheesham Wood King Size Bed (Honey Finish)",
    name_hi: "शीशम वुड किंग साइज बेड (हनी फिनिश)",
    brand: "WoodenStreet",
    category: "Bed",
    price_inr: 38999,
    url: "https://www.woodenstreet.com/search?q=sheesham+king+size+bed+honey",
    description: "Solid sheesham wood king bed in warm honey finish; traditional craftsmanship",
    styles: ["Modern Indian", "Vastu-Optimized"],
  },
  {
    id: "WS002",
    name: "Mango Wood 4-Door Wardrobe (Walnut Finish)",
    name_hi: "मैंगो वुड 4-दरवाजा वॉर्डरोब",
    brand: "WoodenStreet",
    category: "Dresser",
    price_inr: 28999,
    url: "https://www.woodenstreet.com/search?q=mango+wood+4+door+wardrobe+walnut",
    description: "Solid mango wood wardrobe with full mirror; spacious storage for Indian households",
    styles: ["Modern Indian"],
  },
  {
    id: "WS003",
    name: "Solid Wood L-Shaped Study Desk",
    name_hi: "सॉलिड वुड L-शेप स्टडी डेस्क",
    brand: "WoodenStreet",
    category: "Dining Table",
    price_inr: 15999,
    url: "https://www.woodenstreet.com/search?q=l+shaped+study+desk+solid+wood",
    description: "Sheesham wood L-shaped corner desk; large work surface in natural grain",
    styles: ["Modern Indian", "Minimalist"],
  },
  {
    id: "WS004",
    name: "Sheesham Wood Rocking Chair",
    name_hi: "शीशम वुड रॉकिंग चेयर",
    brand: "WoodenStreet",
    category: "Chair",
    price_inr: 11999,
    url: "https://www.woodenstreet.com/search?q=sheesham+rocking+chair",
    description: "Classic solid sheesham rocking chair; traditional comfort with natural wood grain",
    styles: ["Modern Indian", "Vastu-Optimized"],
  },
  {
    id: "WS005",
    name: "Solid Wood Bedside Table with Drawer (Set of 2)",
    name_hi: "सॉलिड वुड बेडसाइड टेबल (2 का सेट)",
    brand: "WoodenStreet",
    category: "Side Table",
    price_inr: 8999,
    url: "https://www.woodenstreet.com/search?q=bedside+table+with+drawer+solid+wood+set+of+2",
    description: "Pair of solid wood nightstands with drawer; matching grain and finish",
    styles: ["Modern Indian", "Minimalist"],
  },

  // ── WAKEFIT ────────────────────────────────────────────────────────
  {
    id: "WF001",
    name: "Wakefit Orthopaedic Memory Foam Mattress (Queen, 6-inch)",
    name_hi: "वेकफिट ऑर्थोपेडिक मेमोरी फोम मैट्रेस (क्वीन)",
    brand: "Wakefit",
    category: "Mattress",
    price_inr: 12999,
    url: "https://www.wakefit.co/mattresses",
    description: "7-zone orthopaedic memory foam mattress; 100-night trial, recommended by physios",
    styles: ["Minimalist", "Vastu-Optimized"],
  },
  {
    id: "WF002",
    name: "Wakefit Hydraulic Storage Bed (Queen, Fabric Headboard)",
    name_hi: "वेकफिट हाइड्रोलिक स्टोरेज बेड (क्वीन)",
    brand: "Wakefit",
    category: "Bed",
    price_inr: 22999,
    url: "https://www.wakefit.co/beds",
    description: "Hydraulic lift storage bed with upholstered headboard; maximises room space",
    styles: ["Minimalist", "Vastu-Optimized"],
  },
  {
    id: "WF003",
    name: "Wakefit Sofa Cum Bed (3-Seater, Grey)",
    name_hi: "वेकफिट सोफा कम बेड (3-सीटर, ग्रे)",
    brand: "Wakefit",
    category: "Sofa",
    price_inr: 19999,
    url: "https://www.wakefit.co/sofa",
    description: "Converts from 3-seater sofa to full-length bed; ideal for studio/guest rooms",
    styles: ["Minimalist"],
  },

  // ── FLIPKART ───────────────────────────────────────────────────────
  {
    id: "FK001",
    name: "Engineered Wood Wall Shelf Set (Set of 3, Walnut)",
    name_hi: "इंजीनियर्ड वुड वॉल शेल्फ (3 का सेट, वॉलनट)",
    brand: "Flipkart",
    category: "Shelving",
    price_inr: 1299,
    url: "https://www.flipkart.com/search?q=wall+shelf+set+of+3+walnut+engineered+wood",
    description: "Floating wall shelves in walnut finish; easy install with hidden brackets",
    styles: ["Minimalist", "Modern Indian"],
  },
  {
    id: "FK002",
    name: "Printed Blackout Curtains (Set of 2, 5 ft, Floral)",
    name_hi: "प्रिंटेड ब्लैकआउट पर्दे (2 का सेट, 5 फीट)",
    brand: "Flipkart",
    category: "Curtains",
    price_inr: 899,
    url: "https://www.flipkart.com/search?q=blackout+curtains+set+of+2+floral+printed",
    description: "Blackout polyester curtains with Indian floral print; blocks 99% of light",
    styles: ["Modern Indian"],
  },
  {
    id: "FK003",
    name: "Faux Leather Recliner Sofa Chair (Brown)",
    name_hi: "फेक्स लेदर रिक्लाइनर चेयर (ब्राउन)",
    brand: "Flipkart",
    category: "Chair",
    price_inr: 8999,
    url: "https://www.flipkart.com/search?q=faux+leather+recliner+sofa+chair+brown",
    description: "Single-seater push-back recliner in faux leather; footrest extends fully",
    styles: ["Modern Indian"],
  },
  {
    id: "FK004",
    name: "Brass Finish Floor Lamp with Marble Base",
    name_hi: "ब्रास फिनिश फ्लोर लैंप (मार्बल बेस)",
    brand: "Flipkart",
    category: "Lighting",
    price_inr: 3499,
    url: "https://www.flipkart.com/search?q=brass+floor+lamp+marble+base+home+decor",
    description: "Antique brass-finish floor lamp with white marble base; warm ambient glow",
    styles: ["Modern Indian", "Vastu-Optimized"],
  },
  {
    id: "FK005",
    name: "Boho Macrame Wall Hanging (Large, 60×90 cm)",
    name_hi: "बोहो मैक्रेमे वॉल हैंगिंग (लार्ज)",
    brand: "Flipkart",
    category: "Wall Art",
    price_inr: 1199,
    url: "https://www.flipkart.com/search?q=boho+macrame+wall+hanging+large+handmade",
    description: "Hand-knotted cotton macramé wall art; bohemian texture adds warmth",
    styles: ["Modern Indian", "Vastu-Optimized"],
  },
];

export function formatCatalogForPrompt(): string {
  return PRODUCT_CATALOG.map(
    (p) =>
      `[${p.id}] ${p.name} | ${p.brand} | ₹${p.price_inr.toLocaleString("en-IN")} | ${p.category} | ${p.description}`
  ).join("\n");
}

export function getProductById(id: string): CatalogProduct | undefined {
  return PRODUCT_CATALOG.find((p) => p.id === id);
}
